#!/bin/bash

function log() {
	echo -e "\033[33;7m$1\033[0m $2"
}

log "> Docs Hook started"

log "Verify we have an up to date release build to generate the docs with"
cargo build --release

pushd docs

log "Build docs"
../target/release/sl-sh docify.lisp index.markdown :lang

if [[ $? != "0" ]]; then
	echo "Uncategorized forms found, not pushing. Please edit appropriate"
	echo "docstrings printed as hashmap literals above. Run"
	echo "$ cd docs && sl-sh docify.lisp index.markdown :lang to get started."
	exit 1;
fi

REMOTE=$(git config --get remote.origin.url)

if [ ! -d ".git" ]; then
   git init
fi

log "Push docs"
if [[ ! $(git remote) ]]; then
	git remote add origin ${REMOTE}
	git add --all && git commit -m "Build $(date)" && git push -u -f origin master
else
	git add . && git commit -m "Build" && git push -f origin master
fi

rm -rf .git

popd doc

log "< Docs Hook finished"
